[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/v1/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true