import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/alpha/image_1.png',
    title: 'Kasir POS (Mobile/HP)',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Aplikasi',
  },
  {
    id: 2,
    cover: '/images/alpha/image_1.png',
    title: 'Kasir POS (Tablet)',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Aplikasi',
  },
  {
    id: 3,
    cover: '/images/alpha/image_1.png',
    title: 'Kasir POS (Desktop)',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Aplikasi',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Promosi (Landing Page)',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Promosi',
  },
  {
    id: 5,
    cover: '/images/alpha/e_commerce_1.png',
    title: 'Penjualan E-Commerce',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Promosi',
  },
  {
    id: 6,
    cover: '/images/alpha/buku_kas_1.png',
    title: 'Buku Kas',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Kas',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Aplikasi Inventori',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Aplikasi',
  },
  {
    id: 8,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Desain Poster',
    rating: 5,
    ratingCount: 10,
    price: 30,
    category: 'Desain',
  },
  {
    id: 9,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Desain Brosur',
    rating: 5,
    ratingCount: 10,
    price: 30,
    category: 'Desain',
  },
  {
    id: 10,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Foto Produk',
    rating: 5,
    ratingCount: 10,
    price: 30,
    category: 'Foto Produk',
  },
  {
    id: 11,
    cover: '/images/alpha/lspmkbi.png',
    title: 'LSP MKBI',
    rating: 5,
    ratingCount: 10,
    price: 30,
    category: 'Website',
  },
  {
    id: 12,
    cover: '/images/alpha/sepatu_1.png',
    title: 'Website sepatu',
    rating: 5,
    ratingCount: 10,
    price: 30,
    category: 'Website',
  }
]
